NVCC=nvcc
CXXFLAGS=-std=c++14 -ltiff

INPUT_DATA_PATH="$(INPUT_DATA_PATH)"
OUTPUT_DATA_PATH="$(OUTPUT_DATA_PATH)"
METHOD="$(METHOD)"


all:
	$(NVCC) -g ./src/*.cu -o ./src/main $(CXXFLAGS)

run:
	./src/main $(INPUT_DATA_PATH)/B2.tif $(INPUT_DATA_PATH)/B3.tif $(INPUT_DATA_PATH)/B4.tif $(INPUT_DATA_PATH)/B5.tif $(INPUT_DATA_PATH)/B6.tif $(INPUT_DATA_PATH)/B10.tif $(INPUT_DATA_PATH)/B7.tif $(INPUT_DATA_PATH)/final_tal.tif $(INPUT_DATA_PATH)/MTL.txt $(INPUT_DATA_PATH)/station.csv -meth=$(METHOD) -nan=-3.39999995214436425e+38
