GCC=g++
CXXFLAGS=-std=c++14 -ltiff

INPUT_DATA_PATH="$(INPUT_DATA_PATH)"
OUTPUT_DATA_PATH="$(OUTPUT_DATA_PATH)"
METHOD="$(METHOD)"
LANDCOVER_DATA_FILE=""

all:
	$(GCC) -g ./src/*.cpp -o ./src/main $(CXXFLAGS)

run LC08:
	./src/main $(INPUT_DATA_PATH)/B2.tif $(INPUT_DATA_PATH)/B3.tif $(INPUT_DATA_PATH)/B4.tif $(INPUT_DATA_PATH)/B5.tif $(INPUT_DATA_PATH)/B6.tif $(INPUT_DATA_PATH)/B10.tif $(INPUT_DATA_PATH)/B7.tif $(INPUT_DATA_PATH)/final_tal.tif $(INPUT_DATA_PATH)/MTL.txt $(INPUT_DATA_PATH)/station.csv $(LANDCOVER_DATA_FILE) $(OUTPUT_DATA_PATH) -meth=$(METHOD) -nan=-3.39999995214436425e+38

run TM05:
	./src/main $(INPUT_DATA_PATH)/B1.tif $(INPUT_DATA_PATH)/B2.tif $(INPUT_DATA_PATH)/B3.tif $(INPUT_DATA_PATH)/B4.tif $(INPUT_DATA_PATH)/B5.tif $(INPUT_DATA_PATH)/B6.tif $(INPUT_DATA_PATH)/B7.tif $(INPUT_DATA_PATH)/final_tal.tif $(INPUT_DATA_PATH)/MTL.txt $(INPUT_DATA_PATH)/station.csv $(LANDCOVER_DATA_FILE) $(OUTPUT_DATA_PATH) -meth=$(METHOD) -nan=-3.39999995214436425e+38